### ISSUE TITLE
Spelling/ Grammar Updates

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_core_guides#113]
The below spelling and grammar typos need to be resolved within the Core Guides. The Observed Behavior / Expected Behavior are listed for each file:

File: docs/Developer Documentation/Transport Manager/index.md

- the the --> the 
- it's --> its (3 times) 

File: docs/Feature Documentation/Smart Objects/index.md

- suceed --> succeed

File: docs/Feature Documentation/Remote Control/index.md

- the the --> the

**Comment by jacobkeeler** [comment]
Closing with the merge of #114
