### ISSUE TITLE
Update cMake Documentation 

### ISSUE THREAD

**Issue by daishah** [smartdevicelink/sdl_core_guides#128]
In an effort to make the cMake Build process an “easier” read, made the following changes to the documentation to include an example of how to build Core from scratch using the HTTP Feature Support Option.

- Bold outside in the building section:
Begin by creating a build folder **outside** of SDL Core source folder, for example:

- And, added cd .. to the example:
cd..
mkdir ../sdl_build
cd ../sdl_build

- Change make install statement:

make install -j3
make install

- Add an example on how to build Core using the HTTP Feature Support Option:

## A cMake Exercise

To Build Core using the HTTP Feature Support Option, do the following:

### **NOTE:** If you have already built Core , be sure to remove the existing build by executing the following steps:

```
rm -rf sdl_core
rm -rf build
```
## From the command line run:

```
sudo apt-get install git cmake build-essential sqlite3 libsqlite3-dev libssl-dev libssl1.1 libusb-1.0-0-dev libudev-dev libgtest-dev libbluetooth3 libbluetooth-dev bluez-tools libpulse-dev python3-pip python3-setuptools python
```
Execute This Line:

```
git clone https://github.com/smartdevicelink/sdl_core
```
Now, Execute This Line:

```
cd sdl_core
```

Execute This Line:

```
git checkout develop
```
Execut This Line:

```
git submodule init
```

Execute This Line:

```
git submodule update
```

Next Step is to Create BUILD folder **outside** of core build:
cd..
mkdir build
cd build

Execute This Line - This will build core using the HTTP option:

```
cmake ../sdl_core -DEXTENDED_POLICY=HTTP
```

Now, Execute This Line:

```
make -j3
```
And finally Execute this Line:

```
make install
```
You have successfully built Core using the HTTP Feature Support Option!

**Comment by jacobkeeler** [comment]
Closing via #129
