### ISSUE TITLE
Grammatical errors and broken link updates

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_core_guides#136]
The following items need to be updated in the Core Guides:

- [result code](https://smartdevicelink.com/en/guides/hmi/common/enums/#result) is a broken link and should be [result code](https://smartdevicelink.com/en/docs/hmi/master/common/enums/#result)
- `and and` in docs/Integrating Your HMI/Developing the HMI UI/index.md should be `and`

**Comment by jacobkeeler** [comment]
Closed via #137
