### ISSUE TITLE
SDL 4.1 documentation is missing

### ISSUE THREAD

**Issue by drauhut** [smartdevicelink/sdl_core_guides#18]
With SDL 4.1 some new RPC's were introduced. The description of those RPC's is missing in the Integration Guidelines. The following RPC's are affected.

OnSystemInfoChanged
OnEventChanged
ShowCustomForm
OnSystemError
AddStatisticsInfo

**Comment by jacobkeeler** [comment]
Removed RPCs that now have documentation. Moving issue to sdl_hmi_integration_guidelines, since this issue applies to that repository
