### ISSUE TITLE
Wrong description on the activate request example

### ISSUE THREAD

**Issue by chinlin0924** [smartdevicelink/sdl_core_guides#3]
It is inside https://smartdevicelink.com/docs/hmi/master/basiccommunication/activateapp/

Check the following description:
Example Request

``` json
{
  "id" : 47,
  "jsonrpc" : "2.0",
  "method" : "BasicCommunication.ActivateApp",
  "result" :
  {
    "appID" : 65368
  }
}
```

this is not example request.

**Comment by justinjdickow** [comment]
@chinlin0924 Can you point out what is not correct about this request specifically?

**Comment by chinlin0924** [comment]
@justinjdickow I think the example has "result", so this is not a result, but a response.

**Comment by chinlin0924** [comment]
@justinjdickow did you understand what I mean?

**Comment by BrandonHe** [comment]
@chinlin0924 @justinjdickow 
I also think it should change **Example Request** from:
```
"result" :
{
   "appID" : 65368
}
```
 to 
```
"params" :
{
   "appID" : 65368
}
```
if I am right, same error exits in document [SDL_Integration_Guidelines_4.0](https://app.box.com/s/ohcgjv61cykgkuhycglju6cc4efr0ym3), 6.2.5.1 Request. it also used ```"result" :```

**Comment by chinlin0924** [comment]
yes! that is very obvious error!

**Comment by Jack-Byrne** [comment]
Closing since this is fixed. Also this issue should have been reported in the HMI Integration guidelines repo.

**Comment by justinjdickow** [comment]
🥳
