### ISSUE TITLE
Add information for H.264 over RTP

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core_guides#39]
Need to add instructions for H.264 over RTP format support for video streaming to the Core Guides.  This should provide the steps necessary to allow Core to handle an RTP stream.

This information should be added to the Core Guides in advance of the Core 4.4 Release (October 30, 2017).

More information about H.264 over RTP feature can be found in the [Evolution Proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0048-H264-over-RTP-support-for-video-streaming.md).

**Comment by jacobkeeler** [comment]
Closing with the merge of #40
