### ISSUE TITLE
Missing shared library `libemhashmap.so.0` during 

### ISSUE THREAD

**Issue by SylvainDe** [smartdevicelink/sdl_core_guides#47]
Hello,
This is an issue as much as a way to document my findings if anyone has the same problem.
Following the build/install/run procedure on latest commit ( https://github.com/smartdevicelink/sdl_core/commit/6212599da217e95899d63d4b33088082489841bd ) , I ran into the following error :

`
$ ./start.sh 
./smartDeviceLinkCore: error while loading shared libraries: libemhashmap.so.0: cannot open shared object file: No such file or directory
`

Installing libbson (`sudo apt-get install libbson-1.0-0 libbson-dev` - probably just one of them is required but I do not know which one...) did fix issue but I am not 100% concince this is the right solution.

If it is, it is probably worth adding libbson to the list on https://smartdevicelink.com/en/guides/core/faq/ . If it is not, I'll take any suggestion.

Also, as I am not sure if this is considered a documentation issue or a build issue, I am not quite sure where to open this issue...

Regards

**Comment by LuxoftAKutsan** [comment]
@SylvainDe please try do ldconfig after sdl build.

**Comment by SylvainDe** [comment]
Thanks @LuxoftAKutsan , I'll try this asap! :+1:

**Comment by jacobkeeler** [comment]
Do not install libbson via a package manager, the one used by Core is a custom project: https://github.com/smartdevicelink/bson_c_lib
